export const ENV_VARS = {
  PORT: 'PORT',
  MONGODB_USER: 'MONGODB_USER',
  MONGODB_PASSWORD: 'MONGODB_PASSWORD',
  MONGODB_URL: 'MONGODB_URL',
  MONGODB_DB: 'MONGODB_DB',

  JWT_SECRET: 'JWT_SECRET',

  APP_DOMAIN: 'APP_DOMAIN',

  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',

  FILE_SAVING_STRATEGY: 'FILE_SAVING_STRATEGY',
};

export const SORT_ORDER = {
  ASC: 'asc',
  DESC: 'desc',
};
