openapi: 3.1.0
info:
  version: 1.0.0
  title: Harmoniq API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 
    This is a documentation of Harmoniq API
tags:
  - name: User
    description: User operations.
  - name: Auth
    description: Auth operations.
  - name: Articles
    description: Operations with articles.
servers:
  - url: http://localhost:3000
  - url: https://contactsapp-9n3j.onrender.com
# paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer