openapi: 3.1.0
info:
  version: 1.0.0
  title: Harmoniq API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Harmoniq API
tags:
  - name: User
    description: User operations.
  - name: Auth
    description: Auth operations.
  - name: Articles
    description: Operations with articles.
servers:
  - url: http://localhost:3008
  - url: https://project-dreamteam-backend.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/refresh:
    get:
      $ref: ../swagger/paths/auth/refresh/get.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
