openapi: 3.1.0
info:
  version: 1.0.0
  title: Harmoniq API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Harmoniq API
tags:
  - name: User
    description: User operations.
  - name: Auth
    description: Auth operations.
  - name: Articles
    description: Operations with articles.
servers:
  - url: https://project-dreamteam-backend.onrender.com
paths:
  # Authentication
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/refresh:
    get:
      $ref: ../swagger/paths/auth/refresh/get.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  # User operations
  /top-authors:
    get:
      $ref: ../swagger/paths/top-authors/get.yaml
  /users/{userId}:
    get:
      $ref: ../swagger/paths/users/{userId}/get.yaml
  /users/{userId}/articles:
    get:
      $ref: ../swagger/paths/users/{userId}/articles/get.yaml
  /bookmarks:
    get:
      $ref: ../swagger/paths/bookmarks/get.yaml
  /bookmarks/add/{articleId}:
    patch:
      $ref: ../swagger/paths/bookmarks/add/{articleId}/patch.yaml
  /bookmarks/remove/{articleId}:
    patch:
      $ref: ../swagger/paths/bookmarks/remove/{articleId}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
